username = input("Ваше имя: ")
title = input("Название заметки: ")
content = input("Описание заметки: ")
status = input("Статус заметки: ")
created_date = input("Дата создания (в формате ДД-ММ-ГГ): ")
issue_date = input("Дата завершения (в формате ДД-ММ-ГГ): ")